// ==UserScript==
// @name          Telegram Solarized Dark Grey
// @namespace     http://userstyles.org
// @description	  Telegram Web style inspired by Solarized Dark color palette designed by Ethan Schoonover.
// @author        ristomatti
// @homepage      https://userstyles.org/styles/125669
// @include       https://web.telegram.org/*
// @run-at        document-start
// @version       0.20170106135019
// ==/UserScript==
(function() {var css = [ ""
	, "/**"
	, "* Telegram Solarized Dark Grey v0.5 (2016-12-27)"
	, "*"
	, "* https://userstyles.org/styles/125669/telegram-solarized-dark-grey"
	, "* https://github.com/ristomatti/telegram-solarized-dark"
	, "*"
	, "* The MIT License (MIT) https://opensource.org/licenses/MIT"
	, "*"
	, "* (c) 2017 Ristomatti Airo <ristomatti@kallio.io>"
	, "*"
	, "* Contributors: Aljosha Balitzki (albalitz)"
	, "*               Alexander Weidinger (irgendwie)"
	, "*/"
	, "/**"
	, "* Solarized Dark Grey LESS color palette v0.1"
	, "*"
	, "* The MIT License (MIT) https://opensource.org/licenses/MIT"
	, "*"
	, "* (c) 2016 Ristomatti Airo <ristomatti@kallio.io>"
	, "*"
	, "* Solarized dark grey colors"
	, "*/"
	, ":root {"
	, "   --background0:  #141414;"
	, "   --background1:  #212121;"
	, "   --background2:  #2e2e2e;"
	, "   --background3:  #3a3a3a;"
	, "   --background4:  #181818;"
	, "/*"
	, "* Solarized dark base colors"
	, "*/"
	, "   --base03:       #002b36;"
	, "   --base02:       #073642;"
	, "   --base01:       #586e75;"
	, "   --base00:       #657b83;"
	, "   --base0:        #839496;"
	, "   --base1:        #93a1a1;"
	, "   --base2:        #eee8d5;"
	, "   --base3:        #fdf6e3;"
	, "/*"
	, "* Solarized accent colors"
	, "*/"
	, "   --yellow:       #b58900;"
	, "   --orange:       #cb4b16;"
	, "   --red:          #dc322f;"
	, "   --magenta:      #d33682;"
	, "   --violet:       #6c71c4;"
	, "   --blue:         #268bd2;"
	, "   --cyan:         #2aa198;"
	, "   --green:        #859900;"
	, "}"
	, "::-webkit-scrollbar {"
	, "  max-width: 10px !important;"
	, "  max-height: 10px !important;"
	, "  background: var(--background4) !important;"
	, "}"
	, "::-webkit-scrollbar-track,"
	, "::-webkit-scrollbar-corner {"
	, "  background: var(--background4) !important;"
	, "}"
	, "::-webkit-scrollbar-thumb {"
	, "  border-radius: 5px !important;"
	, "  background: rgba(80, 80, 80, 0.6) !important;"
	, "}"
	, "::-webkit-scrollbar-thumb:hover {"
	, "  background: rgba(96, 96, 96, 0.6) !important;"
	, "}"
	, "code,"
	, "pre {"
	, "  background-color: var(--background3);"
	, "  color: white;"
	, "}"
	, "pre {"
	, "  border: none;"
	, "}"
	, "body {"
	, "  background-color: var(--background0) !important;"
	, "  color: var(--base0) !important;"
	, "}"
	, ".user_bgcolor_1 {"
	, "  background: var(--violet) !important;"
	, "}"
	, ".user_bgcolor_2 {"
	, "  background: var(--green) !important;"
	, "}"
	, ".user_bgcolor_3 {"
	, "  background: var(--yellow) !important;"
	, "}"
	, ".user_bgcolor_4 {"
	, "  background: var(--blue) !important;"
	, "}"
	, ".user_bgcolor_5 {"
	, "  background: var(--red) !important;"
	, "}"
	, ".user_bgcolor_6 {"
	, "  background: var(--magenta) !important;"
	, "}"
	, ".user_bgcolor_7 {"
	, "  background: var(--cyan) !important;"
	, "}"
	, ".user_bgcolor_8 {"
	, "  background: var(--orange) !important;"
	, "}"
	, ".im_page_wrap {"
	, "  background-color: var(--background0) !important;"
	, "  color: var(--base0) !important;"
	, "  border-left: 1px solid var(--background2) !important;"
	, "  border-right: 1px solid var(--background2) !important;"
	, "  border-bottom: 1px solid var(--background2) !important;"
	, "  box-shadow: none !important;"
	, "}"
	, ".tg_page_head .tg_head_split,"
	, ".tg_page_head .navbar {"
	, "  background-color: var(--background2) !important;"
	, "}"
	, ".im_dialogs_col_wrap {"
	, "  background-color: var(--background0) !important;"
	, "  border-right: 2px solid var(--background2) !important;"
	, "}"
	, ".im_dialogs_col_wrap input.im_dialogs_search_field {"
	, "  background-color: var(--background1) !important;"
	, "  border: 1px solid var(--background3) !important;"
	, "}"
	, ".im_dialogs_col .im_dialog_wrap a.im_dialog {"
	, "  border-top: 1px solid var(--background3) !important;"
	, "  border-bottom: 1px solid var(--background3) !important;"
	, "}"
	, ".im_dialogs_col .im_dialog_wrap.active a.im_dialog {"
	, "  background-color: var(--background2) !important;"
	, "}"
	, ".im_dialogs_col .im_dialog_wrap a.im_dialog:hover {"
	, "  background-color: var(--background1) !important;"
	, "}"
	, ".im_dialogs_col .im_dialog_wrap .im_dialog_message_wrap .im_dialog_peer {"
	, "  color: #cad0d0 !important;"
	, "}"
	, ".im_dialogs_col .im_dialog_wrap .im_dialog_message_wrap .im_dialog_chat_from {"
	, "  color: var(--orange) !important;"
	, "}"
	, ".im_dialogs_col .im_dialog_wrap .im_dialog_message_wrap .im_dialog_message_text {"
	, "  color: var(--base1) !important;"
	, "}"
	, ".im_message_wrap {"
	, "  background-color: var(--background0) !important;"
	, "  color: var(--base0) !important;"
	, "}"
	, ".im_message_wrap .im_message_text {"
	, "  color: var(--base1) !important;"
	, "}"
	, ".im_message_wrap .im_message_unread .icon-message-status {"
	, "  background: var(--yellow);"
	, "}"
	, ".im_message_wrap a {"
	, "  color: var(--orange);"
	, "  text-decoration: none;"
	, "}"
	, ".im_message_unread_split,"
	, ".im_message_date_split,"
	, ".im_service_message {"
	, "  background-color: var(--background1) !important;"
	, "  color: var(--base2) !important;"
	, "}"
	, ".mobile_scrollable_wrap .im_message_wrap .im_message_body {"
	, "  background-color: var(--background1) !important;"
	, "  padding: 7px 10px;"
	, "  border-radius: 0px;"
	, "}"
	, ".mobile_scrollable_wrap .im_message_wrap .im_message_text {"
	, "  line-height: 140%;"
	, "  font-size: 14px;"
	, "}"
	, ".im_bottom_panel_wrap .form-control,"
	, ".im_bottom_panel_wrap .composer_rich_textarea:hover,"
	, ".im_bottom_panel_wrap .composer_rich_textarea:active,"
	, ".im_bottom_panel_wrap .composer_rich_textarea:focus,"
	, ".im_bottom_panel_wrap .composer_rich_textarea:empty {"
	, "  box-shadow: none !important;"
	, "  border-color: var(--background1);"
	, "}"
	, ".im_bottom_panel_wrap .composer_rich_textarea:active,"
	, ".im_bottom_panel_wrap .composer_rich_textarea:empty {"
	, "  background: var(--background0) !important;"
	, "}"
	, ".im_bottom_panel_wrap .composer_rich_textarea:hover,"
	, ".im_bottom_panel_wrap .composer_rich_textarea:focus {"
	, "  background: var(--background0) !important;"
	, "}"
	, ".im_history_pinned_wrap,"
	, ".im_edit_panel_border {"
	, "  border-bottom-color: var(--base01) !important;"
	, "}"
	, ".im_dialog_badge_muted {"
	, "  color: var(--background3) !important;"
	, "}"
	, ".reply_markup_button {"
	, "  background: var(--background2) !important;"
	, "}"
	, ".im_record_bg {"
	, "  background: none !important;"
	, "}"
	, ".icon_tooltip_tail,"
	, ".composer_emoji_tooltip {"
	, "  border-color: var(--background0) !important;"
	, "  background: var(--background1) !important;"
	, "}"
	, ".composer_emoji_tooltip_category i {"
	, "  filter: invert(100%);"
	, "}"
].join("\n");
if (typeof GM_addStyle != "undefined") {
	GM_addStyle(css);
} else if (typeof PRO_addStyle != "undefined") {
	PRO_addStyle(css);
} else if (typeof addStyle != "undefined") {
	addStyle(css);
} else {
	var node = document.createElement("style");
	node.type = "text/css";
	node.appendChild(document.createTextNode(css));
	var heads = document.getElementsByTagName("head");
	if (heads.length > 0) {
		heads[0].appendChild(node);
	} else {
		// no head yet, stick it whereever
		document.documentElement.appendChild(node);
	}
}
})();
