#!/bin/bash

if [ `systemctl --user is-active mpd` != "active" ] ; then
	echo OFF
	exit 0
fi
exec 5<<< $(unset MPD_HOST ; mpc current -f "%artist%\n%title%\n%file%") 
read -u 5 -r artist
read -u 5 -r title
read -u 5 -r filename

# echo "<span color='red'>$artist</span> - <span color='#0000ff'>$title</span>"
if [[ "$filename" =~ 'http' ]] ; then
	# artist="${title%% - *}"
	# title="${title#* - }"
	radio="${filename#http*//}"
	radio="${radio%:*}"
	radio="${radio%/*}"
	echo "$title [$radio]"
elif [ -z "$artist" -o -z "$title" ] ; then
	echo "$filename"
else
	echo "$artist - $title"
fi

exit 0

echo "artist = $artist"
echo "title = $title"
echo "file = $filename"

