#!/bin/bash

if [ `systemctl --user is-active mpd` != "active" ] ; then
	echo OFF
	exit 0
fi
exec 5<<< $(unset MPD_HOST ; mpc current -f "%artist%\n%title%\n%file%") 
read -u 5 -r artist
read -u 5 -r title
read -u 5 -r filename

[[ "$filename" =~ 'dubstep-light.info' ]] && artist="${title%% - *}" && title="${title#* - }"
# TODO case with filename-only string

# echo "<span color='red'>$artist</span> - <span color='#0000ff'>$title</span>"
echo "$artist - $title"

exit 0

echo "artist = $artist"
echo "title = $title"
echo "file = $filename"

